/* ================================================================
   abilities-data.js — ความสามารถ (Ability/Passive) ประจำตัวจริงของแต่ละสายพันธุ์
   ข้อมูลดึงจาก PokeAPI (ความสามารถช่องแรก/สลอต 1 ของแต่ละตัว) ครบ 1025 ตัว
   ABILITY_DEFS: ชื่อจริง (อังกฤษ) + คำอธิบายไทย + เอฟเฟกต์ที่ระบบต่อสู้รองรับ
     - boostType: ท่าธาตุนั้นแรงขึ้น ×1.5 เมื่อ HP≤1/3
     - onHitStatus/onHitChance: โดนโจมตีแบบสัมผัสแล้วศัตรูมีโอกาสติดสถานะ
     - immuneType: ต้านท่าธาตุนั้นสมบูรณ์ (ดาเมจ 0)
     - fx: แท็กเอฟเฟกต์ที่ระบบเช็ค (sturdy/intimidate/insomnia/adaptability/icebody/sandveil/clearbody/serenegrace/guts/multiscale)
   ที่ไม่มีเอฟเฟกต์ = โชว์ชื่อ+คำอธิบายจริง (ยังไม่มีผลกลไกในเกมนี้)
   ================================================================ */

export const ABILITY_DEFS = {
  overgrow: { name: 'Overgrow', desc: 'ท่าธาตุพืชแรงขึ้น ×1.5 เมื่อ HP≤1/3', boostType: 'grass' },
  blaze: { name: 'Blaze', desc: 'ท่าธาตุไฟแรงขึ้น ×1.5 เมื่อ HP≤1/3', boostType: 'fire' },
  torrent: { name: 'Torrent', desc: 'ท่าธาตุน้ำแรงขึ้น ×1.5 เมื่อ HP≤1/3', boostType: 'water' },
  swarm: { name: 'Swarm', desc: 'ท่าธาตุแมลงแรงขึ้น ×1.5 เมื่อ HP≤1/3', boostType: 'bug' },
  static: { name: 'Static', desc: '30% ทำให้ศัตรูที่โจมตีสัมผัสติดอัมพาต', onHitStatus: 'para', onHitChance: 0.3 },
  'poison-point': { name: 'Poison Point', desc: '30% ทำให้ศัตรูที่โจมตีสัมผัสติดพิษ', onHitStatus: 'poison', onHitChance: 0.3 },
  'flame-body': { name: 'Flame Body', desc: '30% ทำให้ศัตรูที่โจมตีสัมผัสติดไหม้', onHitStatus: 'burn', onHitChance: 0.3 },
  'effect-spore': { name: 'Effect Spore', desc: '30% ทำให้ศัตรูที่โจมตีสัมผัสติดสถานะผิดปกติ', onHitStatus: 'poison', onHitChance: 0.3 },
  levitate: { name: 'Levitate', desc: 'ลอยตัว ต้านท่าธาตุดินสมบูรณ์ (ดาเมจ 0)', immuneType: 'ground' },
  'volt-absorb': { name: 'Volt Absorb', desc: 'ต้านท่าธาตุไฟฟ้าสมบูรณ์ (ดาเมจ 0)', immuneType: 'electric' },
  'water-absorb': { name: 'Water Absorb', desc: 'ต้านท่าธาตุน้ำสมบูรณ์ (ดาเมจ 0)', immuneType: 'water' },
  'flash-fire': { name: 'Flash Fire', desc: 'ต้านท่าธาตุไฟสมบูรณ์ (ดาเมจ 0)', immuneType: 'fire' },
  'sap-sipper': { name: 'Sap Sipper', desc: 'ต้านท่าธาตุพืชสมบูรณ์ (ดาเมจ 0)', immuneType: 'grass' },
  'lightning-rod': { name: 'Lightning Rod', desc: 'ดูดท่าธาตุไฟฟ้า ต้านสมบูรณ์ (ดาเมจ 0)', immuneType: 'electric' },
  'motor-drive': { name: 'Motor Drive', desc: 'ต้านท่าธาตุไฟฟ้าสมบูรณ์ (ดาเมจ 0)', immuneType: 'electric' },
  'dry-skin': { name: 'Dry Skin', desc: 'ดูดน้ำ ต้านท่าธาตุน้ำสมบูรณ์ (ดาเมจ 0)', immuneType: 'water' },
  'earth-eater': { name: 'Earth Eater', desc: 'กินดิน ต้านท่าธาตุดินสมบูรณ์ (ดาเมจ 0)', immuneType: 'ground' },
  'well-baked-body': { name: 'Well-Baked Body', desc: 'ต้านท่าธาตุไฟสมบูรณ์ (ดาเมจ 0)', immuneType: 'fire' },
  sturdy: { name: 'Sturdy', desc: 'รอดท่าสังหารครั้งแรกถ้า HP เต็ม', fx: 'sturdy' },
  intimidate: { name: 'Intimidate', desc: 'ตอนลงสนาม ลด ATK ศัตรู 1 ระดับ', fx: 'intimidate' },
  insomnia: { name: 'Insomnia', desc: 'ต้านสถานะหลับสมบูรณ์', fx: 'insomnia' },
  'vital-spirit': { name: 'Vital Spirit', desc: 'ต้านสถานะหลับสมบูรณ์', fx: 'insomnia' },
  'sweet-veil': { name: 'Sweet Veil', desc: 'ต้านสถานะหลับสมบูรณ์', fx: 'insomnia' },
  comatose: { name: 'Comatose', desc: 'หลับตลอดเวลา ต้านสถานะผิดปกติอื่นสมบูรณ์', fx: 'insomnia' },
  'purifying-salt': { name: 'Purifying Salt', desc: 'ต้านสถานะผิดปกติสมบูรณ์', fx: 'insomnia' },
  adaptability: { name: 'Adaptability', desc: 'ท่าธาตุตรง (STAB) แรงขึ้นเป็น ×2', fx: 'adaptability' },
  'ice-body': { name: 'Ice Body', desc: 'ฟื้น HP 1/16 ทุกเทิร์นตอนหิมะโปรย', fx: 'icebody' },
  'sand-veil': { name: 'Sand Veil', desc: 'ตอนพายุทราย ศัตรูที่โจมตีความแม่นยำ -15%', fx: 'sandveil' },
  'clear-body': { name: 'Clear Body', desc: 'ต้านการลดสเตตัสจากศัตรู (รวม Intimidate)', fx: 'clearbody' },
  'white-smoke': { name: 'White Smoke', desc: 'ต้านการลดสเตตัสจากศัตรู', fx: 'clearbody' },
  'full-metal-body': { name: 'Full Metal Body', desc: 'ต้านการลดสเตตัสจากศัตรู', fx: 'clearbody' },
  'serene-grace': { name: 'Serene Grace', desc: 'โอกาสเอฟเฟกต์เสริมจากท่าตัวเอง ×2', fx: 'serenegrace' },
  guts: { name: 'Guts', desc: 'ATK ×1.5 เมื่อติดสถานะผิดปกติ', fx: 'guts' },
  'shadow-shield': { name: 'Shadow Shield', desc: 'ดาเมจที่ได้รับ -50% ตอน HP เต็ม', fx: 'multiscale' },

  // ----- ความสามารถอื่น (โชว์ชื่อจริง + คำอธิบายจริง) -----
  'shield-dust': { name: 'Shield Dust', desc: 'กันเอฟเฟกต์เสริมจากท่าศัตรู' },
  'shed-skin': { name: 'Shed Skin', desc: '33% หายจากสถานะผิดปกติทุกเทิร์น' },
  'compound-eyes': { name: 'Compound Eyes', desc: 'ความแม่นยำท่า +30%' },
  'keen-eye': { name: 'Keen Eye', desc: 'ความแม่นยำไม่ถูกลด' },
  'run-away': { name: 'Run Away', desc: 'หนีจากมอนป่าได้เสมอ' },
  'cute-charm': { name: 'Cute Charm', desc: '30% ศัตรูที่โจมตีสัมผัสติดใจหลงรัก' },
  'inner-focus': { name: 'Inner Focus', desc: 'ไม่สะดุ้ง กันการข่มขวัญ' },
  chlorophyll: { name: 'Chlorophyll', desc: 'ความเร็ว ×2 ตอนแดดจ้า' },
  pickup: { name: 'Pickup', desc: 'มีโอกาสเก็บไอเทมได้หลังสู้' },
  limber: { name: 'Limber', desc: 'ต้านสถานะอัมพาตสมบูรณ์' },
  damp: { name: 'Damp', desc: 'กันท่าระเบิดตัวเอง (Selfdestruct)' },
  synchronize: { name: 'Synchronize', desc: 'ติดสถานะไหม้/พิษ/อัมพาต แล้วส่งให้ศัตรูด้วย' },
  'rock-head': { name: 'Rock Head', desc: 'ไม่บาดเจ็บจากท่ารีคอยล์' },
  oblivious: { name: 'Oblivious', desc: 'กันการหลงรัก/ยั่วยุ' },
  'magnet-pull': { name: 'Magnet Pull', desc: 'ขังโปเกมอนธาตุเหล็กไม่ให้สลับ' },
  'thick-fat': { name: 'Thick Fat', desc: 'ลดดาเมจท่าธาตุไฟ/น้ำแข็งลงครึ่งหนึ่ง' },
  stench: { name: 'Stench', desc: '10% ทำให้ศัตรูสะดุ้งเมื่อโจมตี' },
  'shell-armor': { name: 'Shell Armor', desc: 'กันการโดนคริติคอล' },
  'cursed-body': { name: 'Cursed Body', desc: '30% ล็อกท่าศัตรูที่โจมตี' },
  soundproof: { name: 'Soundproof', desc: 'ต้านท่าเสียงทั้งหมด' },
  'own-tempo': { name: 'Own Tempo', desc: 'กันความสับสน กันการข่มขวัญ' },
  'natural-cure': { name: 'Natural Cure', desc: 'หายจากสถานะผิดปกติเมื่อสลับตัวออก' },
  'early-bird': { name: 'Early Bird', desc: 'ตื่นจากหลับเร็วขึ้น 2 เท่า' },
  'swift-swim': { name: 'Swift Swim', desc: 'ความเร็ว ×2 ตอนฝนตก' },
  illuminate: { name: 'Illuminate', desc: 'ความแม่นยำไม่ถูกลด' },
  trace: { name: 'Trace', desc: 'ก็อปปี้ความสามารถของศัตรูตอนลงสนาม' },
  immunity: { name: 'Immunity', desc: 'ต้านสถานะพิษสมบูรณ์' },
  pressure: { name: 'Pressure', desc: 'ศัตรูเปลือง PP ท่าเป็น 2 เท่า' },
  hustle: { name: 'Hustle', desc: 'ATK ×1.5 แต่ความแม่นยำท่ากายภาพ -20%' },
  'water-veil': { name: 'Water Veil', desc: 'ต้านสถานะไหม้สมบูรณ์' },
  'magma-armor': { name: 'Magma Armor', desc: 'ต้านสถานะแช่แข็งสมบูรณ์' },
  'suction-cups': { name: 'Suction Cups', desc: 'ไม่ถูกบังคับให้สลับตัว' },
  'speed-boost': { name: 'Speed Boost', desc: 'ความเร็ว +1 ทุกเทิร์น' },
  truant: { name: 'Truant', desc: 'โจมตีได้เว้นเทิร์น (พักทุกเทิร์นเว้นเทิร์น)' },
  'wonder-guard': { name: 'Wonder Guard', desc: 'โดนเฉพาะท่าที่ได้เปรียบธาตุ' },
  'pure-power': { name: 'Pure Power', desc: 'พลังโจมตีกายภาพ ×2' },
  plus: { name: 'Plus', desc: 'SpA เพิ่มเมื่อเพื่อนมี Plus/Minus' },
  minus: { name: 'Minus', desc: 'SpA เพิ่มเมื่อเพื่อนมี Plus/Minus' },
  'liquid-ooze': { name: 'Liquid Ooze', desc: 'ศัตรูที่ดูด HP กลับเสีย HP แทน' },
  'rough-skin': { name: 'Rough Skin', desc: 'ศัตรูที่โจมตีสัมผัสเสีย HP 1/8' },
  'battle-armor': { name: 'Battle Armor', desc: 'กันการโดนคริติคอล' },
  'marvel-scale': { name: 'Marvel Scale', desc: 'DEF ×1.5 เมื่อติดสถานะผิดปกติ' },
  forecast: { name: 'Forecast', desc: 'เปลี่ยนธาตุตามสภาพอากาศ' },
  'color-change': { name: 'Color Change', desc: 'เปลี่ยนธาตุเป็นธาตุของท่าที่โดน' },
  'shadow-tag': { name: 'Shadow Tag', desc: 'ขังศัตรูไม่ให้หนี/สลับ' },
  drizzle: { name: 'Drizzle', desc: 'ทำให้ฝนตกตอนลงสนาม' },
  drought: { name: 'Drought', desc: 'ทำให้แดดจ้าตอนลงสนาม' },
  'air-lock': { name: 'Air Lock', desc: 'ลบผลของสภาพอากาศทั้งหมด' },
  simple: { name: 'Simple', desc: 'การเปลี่ยนสเตตัสมีผล 2 เท่า' },
  rivalry: { name: 'Rivalry', desc: 'แรงขึ้นถ้าเพศเดียวกัน อ่อนลงถ้าคนละเพศ' },
  'mold-breaker': { name: 'Mold Breaker', desc: 'เพิกเฉยความสามารถป้องกันของศัตรู' },
  anticipation: { name: 'Anticipation', desc: 'รู้ล่วงหน้าถ้าศัตรูมีท่าอันตราย' },
  'honey-gather': { name: 'Honey Gather', desc: 'มีโอกาสเก็บน้ำผึ้งได้' },
  'flower-gift': { name: 'Flower Gift', desc: 'ATK/SpD ทีม ×1.5 ตอนแดดจ้า' },
  'sticky-hold': { name: 'Sticky Hold', desc: 'ไอเทมที่ถือไม่ถูกขโมย' },
  technician: { name: 'Technician', desc: 'ท่าพลัง≤60 แรงขึ้น ×1.5' },
  aftermath: { name: 'Aftermath', desc: 'ศัตรูที่น็อกด้วยการสัมผัสเสีย HP 1/4' },
  steadfast: { name: 'Steadfast', desc: 'ความเร็ว +1 ทุกครั้งที่สะดุ้ง' },
  'sand-stream': { name: 'Sand Stream', desc: 'ทำให้พายุทรายตอนลงสนาม' },
  'snow-warning': { name: 'Snow Warning', desc: 'ทำให้หิมะตกตอนลงสนาม' },
  'snow-cloak': { name: 'Snow Cloak', desc: 'หลบหลีก +20% ตอนหิมะ' },
  hydration: { name: 'Hydration', desc: 'หายจากสถานะผิดปกติตอนฝนตก' },
  'leaf-guard': { name: 'Leaf Guard', desc: 'กันสถานะผิดปกติตอนแดดจ้า' },
  'bad-dreams': { name: 'Bad Dreams', desc: 'ศัตรูที่หลับเสีย HP ทุกเทิร์น' },
  multitype: { name: 'Multitype', desc: 'เปลี่ยนธาตุตามแผ่นจารึกที่ถือ' },
  'victory-star': { name: 'Victory Star', desc: 'ความแม่นยำทีม +10%' },
  gluttony: { name: 'Gluttony', desc: 'กินเบอร์รี่เร็วขึ้นตอน HP เหลือครึ่ง' },
  forewarn: { name: 'Forewarn', desc: 'รู้ท่าที่แรงที่สุดของศัตรู' },
  'big-pecks': { name: 'Big Pecks', desc: 'DEF ไม่ถูกลดจากศัตรู' },
  unaware: { name: 'Unaware', desc: 'เพิกเฉยการเปลี่ยนสเตตัสของศัตรู' },
  'sand-rush': { name: 'Sand Rush', desc: 'ความเร็ว ×2 ตอนพายุทราย' },
  healer: { name: 'Healer', desc: 'มีโอกาสรักษาสถานะเพื่อนร่วมทีม' },
  prankster: { name: 'Prankster', desc: 'ท่าสถานะได้ priority โจมตีก่อน' },
  reckless: { name: 'Reckless', desc: 'ท่าที่มีรีคอยล์แรงขึ้น ×1.2' },
  'sheer-force': { name: 'Sheer Force', desc: 'ตัดเอฟเฟกต์เสริมทิ้ง แลกพลัง ×1.3' },
  'wonder-skin': { name: 'Wonder Skin', desc: 'ท่าสถานะโดนยากขึ้น' },
  mummy: { name: 'Mummy', desc: 'เปลี่ยนความสามารถศัตรูที่สัมผัสเป็น Mummy' },
  'solid-rock': { name: 'Solid Rock', desc: 'ลดดาเมจท่าที่ได้เปรียบธาตุลง 25%' },
  defeatist: { name: 'Defeatist', desc: 'ATK/SpA ลงครึ่งเมื่อ HP≤ครึ่ง' },
  illusion: { name: 'Illusion', desc: 'ปลอมเป็นตัวสุดท้ายในทีม' },
  frisk: { name: 'Frisk', desc: 'รู้ไอเทมที่ศัตรูถือ' },
  overcoat: { name: 'Overcoat', desc: 'กันดาเมจสภาพอากาศ/ผงสปอร์' },
  'iron-barbs': { name: 'Iron Barbs', desc: 'ศัตรูที่โจมตีสัมผัสเสีย HP 1/8' },
  telepathy: { name: 'Telepathy', desc: 'กันดาเมจจากเพื่อนร่วมทีม' },
  'iron-fist': { name: 'Iron Fist', desc: 'ท่าหมัดแรงขึ้น ×1.2' },
  defiant: { name: 'Defiant', desc: 'ATK +2 เมื่อสเตตัสถูกลดโดยศัตรู' },
  justified: { name: 'Justified', desc: 'ATK +1 เมื่อโดนท่าธาตุมืด' },
  turboblaze: { name: 'Turboblaze', desc: 'เพิกเฉยความสามารถป้องกันของศัตรู' },
  teravolt: { name: 'Teravolt', desc: 'เพิกเฉยความสามารถป้องกันของศัตรู' },
  'sand-force': { name: 'Sand Force', desc: 'ท่าดิน/หิน/เหล็กแรงขึ้นตอนพายุทราย' },
  download: { name: 'Download', desc: 'เพิ่ม ATK หรือ SpA ตามจุดอ่อนศัตรู' },
  'flower-veil': { name: 'Flower Veil', desc: 'กันการลดสเตตัส/สถานะให้ทีมธาตุพืช' },
  contrary: { name: 'Contrary', desc: 'การเปลี่ยนสเตตัสกลับด้าน' },
  'tough-claws': { name: 'Tough Claws', desc: 'ท่าสัมผัสแรงขึ้น ×1.3' },
  'mega-launcher': { name: 'Mega Launcher', desc: 'ท่าคลื่น/ลูกบอลแรงขึ้น ×1.5' },
  'strong-jaw': { name: 'Strong Jaw', desc: 'ท่ากัดแรงขึ้น ×1.5' },
  refrigerate: { name: 'Refrigerate', desc: 'ท่าธรรมดากลายเป็นธาตุน้ำแข็ง +พลัง' },
  'no-guard': { name: 'No Guard', desc: 'ท่าเข้าเป้าเสมอทั้งสองฝ่าย' },
  'stance-change': { name: 'Stance Change', desc: 'สลับร่างรุก/รับตามท่าที่ใช้' },
  'cheek-pouch': { name: 'Cheek Pouch', desc: 'ฟื้น HP เพิ่มเมื่อกินเบอร์รี่' },
  'fur-coat': { name: 'Fur Coat', desc: 'ลดดาเมจท่ากายภาพลงครึ่งหนึ่ง' },
  'fairy-aura': { name: 'Fairy Aura', desc: 'ท่าธาตุแฟรี่ทั้งสนามแรงขึ้น' },
  'dark-aura': { name: 'Dark Aura', desc: 'ท่าธาตุมืดทั้งสนามแรงขึ้น' },
  'aura-break': { name: 'Aura Break', desc: 'กลับด้านผลของออร่า' },
  magician: { name: 'Magician', desc: 'ขโมยไอเทมศัตรูเมื่อโจมตีโดน' },
  stakeout: { name: 'Stakeout', desc: 'ดาเมจ ×2 ต่อศัตรูที่เพิ่งสลับลงมา' },
  battery: { name: 'Battery', desc: 'เพิ่มพลังท่าพิเศษของเพื่อน' },
  dancer: { name: 'Dancer', desc: 'ใช้ท่าเต้นตามศัตรูทันที' },
  schooling: { name: 'Schooling', desc: 'รวมฝูงแข็งแกร่งขึ้นเมื่อ HP สูง' },
  merciless: { name: 'Merciless', desc: 'คริติคอลเสมอต่อศัตรูที่ติดพิษ' },
  'water-bubble': { name: 'Water Bubble', desc: 'ลดดาเมจไฟครึ่ง ท่าน้ำแรง ×2 กันไหม้' },
  corrosion: { name: 'Corrosion', desc: 'วางยาพิษได้แม้ธาตุเหล็ก/พิษ' },
  fluffy: { name: 'Fluffy', desc: 'ลดดาเมจสัมผัสครึ่ง แต่โดนไฟ 2 เท่า' },
  receiver: { name: 'Receiver', desc: 'รับความสามารถของเพื่อนที่ล้ม' },
  'wimp-out': { name: 'Wimp Out', desc: 'สลับตัวออกเมื่อ HP เหลือครึ่ง' },
  'emergency-exit': { name: 'Emergency Exit', desc: 'สลับตัวออกเมื่อ HP เหลือครึ่ง' },
  'water-compaction': { name: 'Water Compaction', desc: 'DEF +2 เมื่อโดนท่าธาตุน้ำ' },
  'innards-out': { name: 'Innards Out', desc: 'ล้มแล้วศัตรูเสีย HP เท่าที่เหลือ' },
  'rks-system': { name: 'RKS System', desc: 'เปลี่ยนธาตุตามแผ่นดิสก์ที่ถือ' },
  'shields-down': { name: 'Shields Down', desc: 'เปลี่ยนร่างเมื่อ HP≤ครึ่ง' },
  disguise: { name: 'Disguise', desc: 'บังเอิญกันดาเมจครั้งแรกได้' },
  dazzling: { name: 'Dazzling', desc: 'กันท่า priority ของศัตรู' },
  berserk: { name: 'Berserk', desc: 'SpA +1 เมื่อ HP เหลือครึ่งจากท่าพิเศษ' },
  steelworker: { name: 'Steelworker', desc: 'ท่าธาตุเหล็กแรงขึ้น ×1.5' },
  bulletproof: { name: 'Bulletproof', desc: 'กันท่าลูกบอล/ลูกระเบิด' },
  'electric-surge': { name: 'Electric Surge', desc: 'สร้างสนามไฟฟ้าตอนลงสนาม' },
  'psychic-surge': { name: 'Psychic Surge', desc: 'สร้างสนามพลังจิตตอนลงสนาม' },
  'grassy-surge': { name: 'Grassy Surge', desc: 'สร้างสนามหญ้าตอนลงสนาม' },
  'misty-surge': { name: 'Misty Surge', desc: 'สร้างสนามหมอกตอนลงสนาม' },
  'beast-boost': { name: 'Beast Boost', desc: 'น็อกศัตรูแล้วสเตตัสเด่นสุด +1' },
  'prism-armor': { name: 'Prism Armor', desc: 'ลดดาเมจท่าที่ได้เปรียบธาตุ 25%' },
  'soul-heart': { name: 'Soul-Heart', desc: 'SpA +1 ทุกครั้งที่มีตัวล้ม' },
  'sand-spit': { name: 'Sand Spit', desc: 'ทำให้พายุทรายเมื่อโดนโจมตี' },
  ripen: { name: 'Ripen', desc: 'ผลของเบอร์รี่เพิ่มเป็น 2 เท่า' },
  'steam-engine': { name: 'Steam Engine', desc: 'ความเร็ว +6 เมื่อโดนท่าไฟ/น้ำ' },
  'ball-fetch': { name: 'Ball Fetch', desc: 'เก็บบอลที่ขว้างพลาดคืนมา' },
  'gulp-missile': { name: 'Gulp Missile', desc: 'สำรอกเหยื่อโจมตีศัตรูหลังใช้ท่าน้ำ' },
  rattled: { name: 'Rattled', desc: 'ความเร็ว +1 เมื่อโดนท่ามืด/ผี/แมลง' },
  'punk-rock': { name: 'Punk Rock', desc: 'ท่าเสียงแรงขึ้น ×1.3 รับครึ่ง' },
  'weak-armor': { name: 'Weak Armor', desc: 'โดนท่ากายภาพ DEF ลง ความเร็วขึ้น' },
  'cotton-down': { name: 'Cotton Down', desc: 'โดนโจมตี ลดความเร็วศัตรูทั้งหมด' },
  'tangled-feet': { name: 'Tangled Feet', desc: 'หลบหลีกเพิ่มตอนสับสน' },
  'wandering-spirit': { name: 'Wandering Spirit', desc: 'สลับความสามารถกับศัตรูที่สัมผัส' },
  'power-spot': { name: 'Power Spot', desc: 'เพิ่มพลังท่าของเพื่อน' },
  'ice-face': { name: 'Ice Face', desc: 'หัวน้ำแข็งกันท่ากายภาพครั้งแรก' },
  'hunger-switch': { name: 'Hunger Switch', desc: 'สลับร่างทุกเทิร์น' },
  'light-metal': { name: 'Light Metal', desc: 'น้ำหนักตัวลดครึ่ง' },
  'intrepid-sword': { name: 'Intrepid Sword', desc: 'ATK +1 ตอนลงสนามครั้งแรก' },
  'dauntless-shield': { name: 'Dauntless Shield', desc: 'DEF +1 ตอนลงสนามครั้งแรก' },
  'unseen-fist': { name: 'Unseen Fist', desc: 'ท่าสัมผัสทะลุการป้องกัน' },
  transistor: { name: 'Transistor', desc: 'ท่าธาตุไฟฟ้าแรงขึ้น ×1.3' },
  'dragons-maw': { name: "Dragon's Maw", desc: 'ท่าธาตุมังกรแรงขึ้น ×1.5' },
  'chilling-neigh': { name: 'Chilling Neigh', desc: 'ATK +1 เมื่อน็อกศัตรู' },
  'grim-neigh': { name: 'Grim Neigh', desc: 'SpA +1 เมื่อน็อกศัตรู' },
  unnerve: { name: 'Unnerve', desc: 'ศัตรูกินเบอร์รี่ไม่ได้' },
  'aroma-veil': { name: 'Aroma Veil', desc: 'กันผลที่จำกัดการใช้ท่าให้ทีม' },
  'lingering-aroma': { name: 'Lingering Aroma', desc: 'เปลี่ยนความสามารถศัตรูที่สัมผัส' },
  'friend-guard': { name: 'Friend Guard', desc: 'ลดดาเมจที่เพื่อนได้รับ' },
  'seed-sower': { name: 'Seed Sower', desc: 'สร้างสนามหญ้าเมื่อโดนโจมตี' },
  electromorphosis: { name: 'Electromorphosis', desc: 'สะสมพลังไฟฟ้าเมื่อโดนโจมตี' },
  'wind-power': { name: 'Wind Power', desc: 'สะสมพลังไฟฟ้าเมื่อโดนท่าลม' },
  unburden: { name: 'Unburden', desc: 'ความเร็ว ×2 หลังใช้/เสียไอเทม' },
  'wind-rider': { name: 'Wind Rider', desc: 'ATK +1 เมื่อโดนท่าลม ต้านลมได้' },
  'mycelium-might': { name: 'Mycelium Might', desc: 'ท่าสถานะทะลุความสามารถศัตรูแต่ช้าลง' },
  'anger-shell': { name: 'Anger Shell', desc: 'HP≤ครึ่ง เพิ่มพลังรุก ลดพลังรับ' },
  opportunist: { name: 'Opportunist', desc: 'ก็อปการเพิ่มสเตตัสของศัตรู' },
  gooey: { name: 'Gooey', desc: 'ศัตรูที่โจมตีสัมผัสความเร็ว -1' },
  'zero-to-hero': { name: 'Zero to Hero', desc: 'เปลี่ยนร่างฮีโร่เมื่อสลับออก' },
  'toxic-debris': { name: 'Toxic Debris', desc: 'วางหนามพิษเมื่อโดนท่ากายภาพ' },
  scrappy: { name: 'Scrappy', desc: 'ท่าปกติ/ต่อสู้โดนธาตุผีได้' },
  commander: { name: 'Commander', desc: 'บัญชาการร่วมกับพันธมิตร' },
  'cud-chew': { name: 'Cud Chew', desc: 'เคี้ยวเบอร์รี่ซ้ำในเทิร์นถัดไป' },
  protosynthesis: { name: 'Protosynthesis', desc: 'สเตตัสเด่นสุดขึ้นตอนแดดจ้า/ถือแคปซูล' },
  'quark-drive': { name: 'Quark Drive', desc: 'สเตตัสเด่นสุดขึ้นในสนามไฟฟ้า/ถือแคปซูล' },
  'thermal-exchange': { name: 'Thermal Exchange', desc: 'ATK +1 เมื่อโดนท่าไฟ กันไหม้' },
  'good-as-gold': { name: 'Good as Gold', desc: 'ต้านท่าสถานะของศัตรูทั้งหมด' },
  'tablets-of-ruin': { name: 'Tablets of Ruin', desc: 'ลด ATK ของตัวอื่นทั้งสนาม' },
  'sword-of-ruin': { name: 'Sword of Ruin', desc: 'ลด DEF ของตัวอื่นทั้งสนาม' },
  'vessel-of-ruin': { name: 'Vessel of Ruin', desc: 'ลด SpA ของตัวอื่นทั้งสนาม' },
  'beads-of-ruin': { name: 'Beads of Ruin', desc: 'ลด SpD ของตัวอื่นทั้งสนาม' },
  'orichalcum-pulse': { name: 'Orichalcum Pulse', desc: 'ทำให้แดดจ้า + ATK สูงตอนแดด' },
  'hadron-engine': { name: 'Hadron Engine', desc: 'สร้างสนามไฟฟ้า + SpA สูง' },
  'supersweet-syrup': { name: 'Supersweet Syrup', desc: 'ลดหลบหลีกศัตรูตอนลงสนาม' },
  hospitality: { name: 'Hospitality', desc: 'ฟื้น HP ให้เพื่อนตอนลงสนาม' },
  'toxic-chain': { name: 'Toxic Chain', desc: '30% ทำให้ศัตรูติดพิษร้ายแรงเมื่อโจมตี' },
  stamina: { name: 'Stamina', desc: 'DEF +1 ทุกครั้งที่โดนโจมตี' },
  'tera-shift': { name: 'Tera Shift', desc: 'เปลี่ยนร่างเทระตอนลงสนาม' },
  'poison-puppeteer': { name: 'Poison Puppeteer', desc: 'ศัตรูที่โดนพิษจากตัวนี้จะสับสนด้วย' },
};

// id → identifier ความสามารถประจำตัว (ช่องแรก) ของแต่ละสายพันธุ์ (จาก PokeAPI)
export const SPECIES_ABILITY = {
1:"overgrow",2:"overgrow",3:"overgrow",4:"blaze",5:"blaze",6:"blaze",7:"torrent",8:"torrent",9:"torrent",10:"shield-dust",11:"shed-skin",12:"compound-eyes",13:"shield-dust",14:"shed-skin",15:"swarm",16:"keen-eye",17:"keen-eye",18:"keen-eye",19:"run-away",20:"run-away",21:"keen-eye",22:"keen-eye",23:"intimidate",24:"intimidate",25:"static",26:"static",27:"sand-veil",28:"sand-veil",29:"poison-point",30:"poison-point",31:"poison-point",32:"poison-point",33:"poison-point",34:"poison-point",35:"cute-charm",36:"cute-charm",37:"flash-fire",38:"flash-fire",39:"cute-charm",40:"cute-charm",41:"inner-focus",42:"inner-focus",43:"chlorophyll",44:"chlorophyll",45:"chlorophyll",46:"effect-spore",47:"effect-spore",48:"compound-eyes",49:"shield-dust",50:"sand-veil",51:"sand-veil",52:"pickup",53:"limber",54:"damp",55:"damp",56:"vital-spirit",57:"vital-spirit",58:"intimidate",59:"intimidate",60:"water-absorb",61:"water-absorb",62:"water-absorb",63:"synchronize",64:"synchronize",65:"synchronize",66:"guts",67:"guts",68:"guts",69:"chlorophyll",70:"chlorophyll",71:"chlorophyll",72:"clear-body",73:"clear-body",74:"rock-head",75:"rock-head",76:"rock-head",77:"run-away",78:"run-away",79:"oblivious",80:"oblivious",81:"magnet-pull",82:"magnet-pull",83:"keen-eye",84:"run-away",85:"run-away",86:"thick-fat",87:"thick-fat",88:"stench",89:"stench",90:"shell-armor",91:"shell-armor",92:"levitate",93:"levitate",94:"cursed-body",95:"rock-head",96:"insomnia",97:"insomnia",98:"hyper-cutter",99:"hyper-cutter",100:"soundproof",101:"soundproof",102:"chlorophyll",103:"chlorophyll",104:"rock-head",105:"rock-head",106:"limber",107:"keen-eye",108:"own-tempo",109:"levitate",110:"levitate",111:"lightning-rod",112:"lightning-rod",113:"natural-cure",114:"chlorophyll",115:"early-bird",116:"swift-swim",117:"poison-point",118:"swift-swim",119:"swift-swim",120:"illuminate",121:"illuminate",122:"soundproof",123:"swarm",124:"oblivious",125:"static",126:"flame-body",127:"hyper-cutter",128:"intimidate",129:"swift-swim",130:"intimidate",131:"water-absorb",132:"limber",133:"run-away",134:"water-absorb",135:"volt-absorb",136:"flash-fire",137:"trace",138:"swift-swim",139:"swift-swim",140:"swift-swim",141:"swift-swim",142:"rock-head",143:"immunity",144:"pressure",145:"pressure",146:"pressure",147:"shed-skin",148:"shed-skin",149:"inner-focus",150:"pressure",151:"synchronize",152:"overgrow",153:"overgrow",154:"overgrow",155:"blaze",156:"blaze",157:"blaze",158:"torrent",159:"torrent",160:"torrent",161:"run-away",162:"run-away",163:"insomnia",164:"insomnia",165:"swarm",166:"swarm",167:"swarm",168:"swarm",169:"inner-focus",170:"volt-absorb",171:"volt-absorb",172:"static",173:"cute-charm",174:"cute-charm",175:"hustle",176:"hustle",177:"synchronize",178:"synchronize",179:"static",180:"static",181:"static",182:"chlorophyll",183:"thick-fat",184:"thick-fat",185:"sturdy",186:"water-absorb",187:"chlorophyll",188:"chlorophyll",189:"chlorophyll",190:"run-away",191:"chlorophyll",192:"chlorophyll",193:"speed-boost",194:"damp",195:"damp",196:"synchronize",197:"synchronize",198:"insomnia",199:"oblivious",200:"levitate",201:"levitate",202:"shadow-tag",203:"inner-focus",204:"sturdy",205:"sturdy",206:"serene-grace",207:"hyper-cutter",208:"rock-head",209:"intimidate",210:"intimidate",211:"poison-point",212:"swarm",213:"sturdy",214:"swarm",215:"inner-focus",216:"pickup",217:"guts",218:"magma-armor",219:"magma-armor",220:"oblivious",221:"oblivious",222:"hustle",223:"hustle",224:"suction-cups",225:"vital-spirit",226:"swift-swim",227:"keen-eye",228:"early-bird",229:"early-bird",230:"swift-swim",231:"pickup",232:"sturdy",233:"trace",234:"intimidate",235:"own-tempo",236:"guts",237:"intimidate",238:"oblivious",239:"static",240:"flame-body",241:"thick-fat",242:"natural-cure",243:"pressure",244:"pressure",245:"pressure",246:"guts",247:"shed-skin",248:"sand-stream",249:"pressure",250:"pressure",251:"natural-cure",252:"overgrow",253:"overgrow",254:"overgrow",255:"blaze",256:"blaze",257:"blaze",258:"torrent",259:"torrent",260:"torrent",261:"run-away",262:"intimidate",263:"pickup",264:"pickup",265:"shield-dust",266:"shed-skin",267:"swarm",268:"shed-skin",269:"shield-dust",270:"swift-swim",271:"swift-swim",272:"swift-swim",273:"chlorophyll",274:"chlorophyll",275:"chlorophyll",276:"guts",277:"guts",278:"keen-eye",279:"keen-eye",280:"synchronize",281:"synchronize",282:"synchronize",283:"swift-swim",284:"intimidate",285:"effect-spore",286:"effect-spore",287:"truant",288:"vital-spirit",289:"truant",290:"compound-eyes",291:"speed-boost",292:"wonder-guard",293:"soundproof",294:"soundproof",295:"soundproof",296:"thick-fat",297:"thick-fat",298:"thick-fat",299:"sturdy",300:"cute-charm",301:"cute-charm",302:"keen-eye",303:"hyper-cutter",304:"sturdy",305:"sturdy",306:"sturdy",307:"pure-power",308:"pure-power",309:"static",310:"static",311:"plus",312:"minus",313:"illuminate",314:"oblivious",315:"natural-cure",316:"liquid-ooze",317:"liquid-ooze",318:"rough-skin",319:"rough-skin",320:"water-veil",321:"water-veil",322:"oblivious",323:"magma-armor",324:"white-smoke",325:"thick-fat",326:"thick-fat",327:"own-tempo",328:"hyper-cutter",329:"levitate",330:"levitate",331:"sand-veil",332:"sand-veil",333:"natural-cure",334:"natural-cure",335:"immunity",336:"shed-skin",337:"levitate",338:"levitate",339:"oblivious",340:"oblivious",341:"hyper-cutter",342:"hyper-cutter",343:"levitate",344:"levitate",345:"suction-cups",346:"suction-cups",347:"battle-armor",348:"battle-armor",349:"swift-swim",350:"marvel-scale",351:"forecast",352:"color-change",353:"insomnia",354:"insomnia",355:"levitate",356:"pressure",357:"chlorophyll",358:"levitate",359:"pressure",360:"shadow-tag",361:"inner-focus",362:"inner-focus",363:"thick-fat",364:"thick-fat",365:"thick-fat",366:"shell-armor",367:"swift-swim",368:"swift-swim",369:"swift-swim",370:"swift-swim",371:"rock-head",372:"rock-head",373:"intimidate",374:"clear-body",375:"clear-body",376:"clear-body",377:"clear-body",378:"clear-body",379:"clear-body",380:"levitate",381:"levitate",382:"drizzle",383:"drought",384:"air-lock",385:"serene-grace",386:"pressure",387:"overgrow",388:"overgrow",389:"overgrow",390:"blaze",391:"blaze",392:"blaze",393:"torrent",394:"torrent",395:"torrent",396:"keen-eye",397:"intimidate",398:"intimidate",399:"simple",400:"simple",401:"shed-skin",402:"swarm",403:"rivalry",404:"rivalry",405:"rivalry",406:"natural-cure",407:"natural-cure",408:"mold-breaker",409:"mold-breaker",410:"sturdy",411:"sturdy",412:"shed-skin",413:"anticipation",414:"swarm",415:"honey-gather",416:"pressure",417:"run-away",418:"swift-swim",419:"swift-swim",420:"chlorophyll",421:"flower-gift",422:"sticky-hold",423:"sticky-hold",424:"technician",425:"aftermath",426:"aftermath",427:"run-away",428:"cute-charm",429:"levitate",430:"insomnia",431:"limber",432:"thick-fat",433:"levitate",434:"stench",435:"stench",436:"levitate",437:"levitate",438:"sturdy",439:"soundproof",440:"natural-cure",441:"keen-eye",442:"pressure",443:"sand-veil",444:"sand-veil",445:"sand-veil",446:"pickup",447:"steadfast",448:"steadfast",449:"sand-stream",450:"sand-stream",451:"battle-armor",452:"battle-armor",453:"anticipation",454:"anticipation",455:"levitate",456:"swift-swim",457:"swift-swim",458:"swift-swim",459:"snow-warning",460:"snow-warning",461:"pressure",462:"magnet-pull",463:"own-tempo",464:"lightning-rod",465:"chlorophyll",466:"motor-drive",467:"flame-body",468:"hustle",469:"speed-boost",470:"leaf-guard",471:"snow-cloak",472:"hyper-cutter",473:"oblivious",474:"adaptability",475:"steadfast",476:"sturdy",477:"pressure",478:"snow-cloak",479:"levitate",480:"levitate",481:"levitate",482:"levitate",483:"pressure",484:"pressure",485:"flash-fire",486:"slow-start",487:"pressure",488:"levitate",489:"hydration",490:"hydration",491:"bad-dreams",492:"natural-cure",493:"multitype",494:"victory-star",495:"overgrow",496:"overgrow",497:"overgrow",498:"blaze",499:"blaze",500:"blaze",501:"torrent",502:"torrent",503:"torrent",504:"run-away",505:"illuminate",506:"vital-spirit",507:"intimidate",508:"intimidate",509:"limber",510:"limber",511:"gluttony",512:"gluttony",513:"gluttony",514:"gluttony",515:"gluttony",516:"gluttony",517:"forewarn",518:"forewarn",519:"big-pecks",520:"big-pecks",521:"big-pecks",522:"lightning-rod",523:"lightning-rod",524:"sturdy",525:"sturdy",526:"sturdy",527:"unaware",528:"unaware",529:"sand-rush",530:"sand-rush",531:"healer",532:"guts",533:"guts",534:"guts",535:"swift-swim",536:"swift-swim",537:"swift-swim",538:"guts",539:"sturdy",540:"swarm",541:"leaf-guard",542:"swarm",543:"poison-point",544:"poison-point",545:"poison-point",546:"prankster",547:"prankster",548:"chlorophyll",549:"chlorophyll",550:"reckless",551:"intimidate",552:"intimidate",553:"intimidate",554:"hustle",555:"sheer-force",556:"water-absorb",557:"sturdy",558:"sturdy",559:"shed-skin",560:"shed-skin",561:"wonder-skin",562:"mummy",563:"mummy",564:"solid-rock",565:"solid-rock",566:"defeatist",567:"defeatist",568:"stench",569:"stench",570:"illusion",571:"illusion",572:"cute-charm",573:"cute-charm",574:"frisk",575:"frisk",576:"frisk",577:"overcoat",578:"overcoat",579:"overcoat",580:"keen-eye",581:"keen-eye",582:"ice-body",583:"ice-body",584:"ice-body",585:"chlorophyll",586:"chlorophyll",587:"static",588:"swarm",589:"swarm",590:"effect-spore",591:"effect-spore",592:"water-absorb",593:"water-absorb",594:"healer",595:"compound-eyes",596:"compound-eyes",597:"iron-barbs",598:"iron-barbs",599:"plus",600:"plus",601:"plus",602:"levitate",603:"levitate",604:"levitate",605:"telepathy",606:"telepathy",607:"flash-fire",608:"flash-fire",609:"flash-fire",610:"rivalry",611:"rivalry",612:"rivalry",613:"snow-cloak",614:"snow-cloak",615:"levitate",616:"hydration",617:"hydration",618:"static",619:"inner-focus",620:"inner-focus",621:"rough-skin",622:"iron-fist",623:"iron-fist",624:"defiant",625:"defiant",626:"reckless",627:"keen-eye",628:"keen-eye",629:"big-pecks",630:"big-pecks",631:"gluttony",632:"swarm",633:"hustle",634:"hustle",635:"levitate",636:"flame-body",637:"flame-body",638:"justified",639:"justified",640:"justified",641:"prankster",642:"prankster",643:"turboblaze",644:"teravolt",645:"sand-force",646:"pressure",647:"justified",648:"serene-grace",649:"download",650:"overgrow",651:"overgrow",652:"overgrow",653:"blaze",654:"blaze",655:"blaze",656:"torrent",657:"torrent",658:"torrent",659:"pickup",660:"pickup",661:"big-pecks",662:"flame-body",663:"flame-body",664:"shield-dust",665:"shed-skin",666:"shield-dust",667:"rivalry",668:"rivalry",669:"flower-veil",670:"flower-veil",671:"flower-veil",672:"sap-sipper",673:"sap-sipper",674:"iron-fist",675:"iron-fist",676:"fur-coat",677:"keen-eye",678:"keen-eye",679:"no-guard",680:"no-guard",681:"stance-change",682:"healer",683:"healer",684:"sweet-veil",685:"sweet-veil",686:"contrary",687:"contrary",688:"tough-claws",689:"tough-claws",690:"poison-point",691:"poison-point",692:"mega-launcher",693:"mega-launcher",694:"dry-skin",695:"dry-skin",696:"strong-jaw",697:"strong-jaw",698:"refrigerate",699:"refrigerate",700:"cute-charm",701:"limber",702:"cheek-pouch",703:"clear-body",704:"sap-sipper",705:"sap-sipper",706:"sap-sipper",707:"prankster",708:"natural-cure",709:"natural-cure",710:"pickup",711:"pickup",712:"own-tempo",713:"own-tempo",714:"frisk",715:"frisk",716:"fairy-aura",717:"dark-aura",718:"aura-break",719:"clear-body",720:"magician",721:"water-absorb",722:"overgrow",723:"overgrow",724:"overgrow",725:"blaze",726:"blaze",727:"blaze",728:"torrent",729:"torrent",730:"torrent",731:"keen-eye",732:"keen-eye",733:"keen-eye",734:"stakeout",735:"stakeout",736:"swarm",737:"battery",738:"levitate",739:"hyper-cutter",740:"hyper-cutter",741:"dancer",742:"honey-gather",743:"honey-gather",744:"keen-eye",745:"keen-eye",746:"schooling",747:"merciless",748:"merciless",749:"own-tempo",750:"own-tempo",751:"water-bubble",752:"water-bubble",753:"leaf-guard",754:"leaf-guard",755:"illuminate",756:"illuminate",757:"corrosion",758:"corrosion",759:"fluffy",760:"fluffy",761:"leaf-guard",762:"leaf-guard",763:"leaf-guard",764:"flower-veil",765:"inner-focus",766:"receiver",767:"wimp-out",768:"emergency-exit",769:"water-compaction",770:"water-compaction",771:"innards-out",772:"battle-armor",773:"rks-system",774:"shields-down",775:"comatose",776:"shell-armor",777:"iron-barbs",778:"disguise",779:"dazzling",780:"berserk",781:"steelworker",782:"bulletproof",783:"bulletproof",784:"bulletproof",785:"electric-surge",786:"psychic-surge",787:"grassy-surge",788:"misty-surge",789:"unaware",790:"sturdy",791:"full-metal-body",792:"shadow-shield",793:"beast-boost",794:"beast-boost",795:"beast-boost",796:"beast-boost",797:"beast-boost",798:"beast-boost",799:"beast-boost",800:"prism-armor",801:"soul-heart",802:"technician",803:"beast-boost",804:"beast-boost",805:"beast-boost",806:"beast-boost",807:"volt-absorb",808:"magnet-pull",809:"iron-fist",810:"overgrow",811:"overgrow",812:"overgrow",813:"blaze",814:"blaze",815:"blaze",816:"torrent",817:"torrent",818:"torrent",819:"cheek-pouch",820:"cheek-pouch",821:"keen-eye",822:"keen-eye",823:"pressure",824:"swarm",825:"swarm",826:"swarm",827:"run-away",828:"run-away",829:"cotton-down",830:"cotton-down",831:"fluffy",832:"fluffy",833:"strong-jaw",834:"strong-jaw",835:"ball-fetch",836:"strong-jaw",837:"steam-engine",838:"steam-engine",839:"steam-engine",840:"ripen",841:"ripen",842:"ripen",843:"sand-spit",844:"sand-spit",845:"gulp-missile",846:"swift-swim",847:"swift-swim",848:"rattled",849:"punk-rock",850:"flash-fire",851:"flash-fire",852:"limber",853:"limber",854:"weak-armor",855:"weak-armor",856:"healer",857:"healer",858:"healer",859:"prankster",860:"prankster",861:"prankster",862:"reckless",863:"battle-armor",864:"weak-armor",865:"steadfast",866:"tangled-feet",867:"wandering-spirit",868:"sweet-veil",869:"sweet-veil",870:"battle-armor",871:"lightning-rod",872:"shield-dust",873:"shield-dust",874:"power-spot",875:"ice-face",876:"inner-focus",877:"hunger-switch",878:"sheer-force",879:"sheer-force",880:"volt-absorb",881:"volt-absorb",882:"water-absorb",883:"water-absorb",884:"light-metal",885:"clear-body",886:"clear-body",887:"clear-body",888:"intrepid-sword",889:"dauntless-shield",890:"pressure",891:"inner-focus",892:"unseen-fist",893:"leaf-guard",894:"transistor",895:"dragons-maw",896:"chilling-neigh",897:"grim-neigh",898:"unnerve",899:"intimidate",900:"swarm",901:"guts",902:"swift-swim",903:"pressure",904:"poison-point",905:"cute-charm",906:"overgrow",907:"overgrow",908:"overgrow",909:"blaze",910:"blaze",911:"blaze",912:"torrent",913:"torrent",914:"torrent",915:"aroma-veil",916:"lingering-aroma",917:"insomnia",918:"insomnia",919:"swarm",920:"swarm",921:"static",922:"volt-absorb",923:"volt-absorb",924:"run-away",925:"friend-guard",926:"own-tempo",927:"well-baked-body",928:"early-bird",929:"early-bird",930:"seed-sower",931:"intimidate",932:"purifying-salt",933:"purifying-salt",934:"purifying-salt",935:"flash-fire",936:"flash-fire",937:"flash-fire",938:"own-tempo",939:"electromorphosis",940:"wind-power",941:"wind-power",942:"intimidate",943:"intimidate",944:"unburden",945:"unburden",946:"wind-rider",947:"wind-rider",948:"mycelium-might",949:"mycelium-might",950:"anger-shell",951:"chlorophyll",952:"chlorophyll",953:"compound-eyes",954:"synchronize",955:"anticipation",956:"opportunist",957:"mold-breaker",958:"mold-breaker",959:"mold-breaker",960:"gooey",961:"gooey",962:"big-pecks",963:"water-veil",964:"zero-to-hero",965:"overcoat",966:"overcoat",967:"shed-skin",968:"earth-eater",969:"toxic-debris",970:"toxic-debris",971:"pickup",972:"sand-rush",973:"scrappy",974:"thick-fat",975:"thick-fat",976:"mold-breaker",977:"unaware",978:"commander",979:"vital-spirit",980:"poison-point",981:"cud-chew",982:"serene-grace",983:"defiant",984:"protosynthesis",985:"protosynthesis",986:"protosynthesis",987:"protosynthesis",988:"protosynthesis",989:"protosynthesis",990:"quark-drive",991:"quark-drive",992:"quark-drive",993:"quark-drive",994:"quark-drive",995:"quark-drive",996:"thermal-exchange",997:"thermal-exchange",998:"thermal-exchange",999:"rattled",1000:"good-as-gold",1001:"tablets-of-ruin",1002:"sword-of-ruin",1003:"vessel-of-ruin",1004:"beads-of-ruin",1005:"protosynthesis",1006:"quark-drive",1007:"orichalcum-pulse",1008:"hadron-engine",1009:"protosynthesis",1010:"quark-drive",1011:"supersweet-syrup",1012:"hospitality",1013:"hospitality",1014:"toxic-chain",1015:"toxic-chain",1016:"toxic-chain",1017:"defiant",1018:"stamina",1019:"supersweet-syrup",1020:"protosynthesis",1021:"protosynthesis",1022:"quark-drive",1023:"quark-drive",1024:"tera-shift",1025:"poison-puppeteer"
};

// hyper-cutter ยังไม่ได้ประกาศใน DEFS (กัน undefined) — ป้องกัน ATK ถูกลด ใกล้เคียง clear body
ABILITY_DEFS['hyper-cutter'] = { name: 'Hyper Cutter', desc: 'ATK ไม่ถูกลดจากศัตรู', fx: 'clearbody' };
ABILITY_DEFS['slow-start'] = { name: 'Slow Start', desc: '5 เทิร์นแรก ATK/ความเร็วลงครึ่ง' };
